#pragma once

void ejercicio_1();
void ejercicio_2();
void ejercicio_3();
void ejercicio_4();
void ejercicio_5();
void ejercicio_6();
void ejercicio_7();
void ejercicio_8();
void ejercicio_9();
void ejercicio_10();
void ejercicio_11();
void ejercicio_12();
void ejercicio_13();
void ejercicio_14();
void ejercicio_15();
void ejercicio_16();
void ejercicio_17();
void ejercicio_18();
void ejercicio_19();
void ejercicio_29();
